package com.orders.entities;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Entity class representing a shopping cart.
 * This class is mapped to a database table where each instance corresponds to a cart entry,
 * including details such as the user who owns the cart, the food item, its quantity, and price.
 * <p>
 * Lombok's {@code @Data} annotation is used to automatically generate
 * getters, setters, equals, hashCode, and toString methods.
 * </p>
 */
@Entity
@Data
public class Cart {

    /**
     * The unique ID of the cart entry.
     * This is the primary key, auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long cartId;

    /**
     * The ID of the user who owns the cart.
     * This acts as a foreign key that references the user (manually handled).
     */
    private Long userId;

    /**
     * The ID of the food item added to the cart.
     * This is fetched via Feign from the Restaurant microservice.
     */
    private Long foodItemId;

    /**
     * The quantity of the food item added to the cart.
     */
    private Integer quantity;

    /**
     * The ID of the restaurant from which the food item is ordered.
     */
    private Long restaurantId;

    /**
     * The price per item of the food item in the cart.
     */
    private Double pricePerItem;

}
